football_db:
  db_name: duckdb:///duck.db
  db_tables: [
            "players",
            "games",
            "clubs",
            "appearances",
            "player_valuations",
            "game_events",
            "club_games"
        ]

llm:
  model_name: gpt-3.5-turbo-0125